name: Angular Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy angular App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Packages
        run: |
          npm install
      - name: Build App
        run: |
          ng build --prod --base-href https://xzodia1000.github.io/anizod/
      - name: Deploy App
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist/anizod
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}